server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cloud-gateway
  cloud: # spring cloud相关配置的常用前缀
    gateway: # 网关技术配置前缀
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # 允许所有来源，可以改为具体的域名
            allowedMethods: "*" # 允许所有 HTTP 方法
            allowedHeaders: "*" # 允许所有请求头
            allowCredentials: true # 允许携带 Cookie
      discovery: # 自动发现工具
        locator: # 本地逻辑
          enabled: true # 开启自动发现工具的本地路由逻辑
          lower-case-service-id: true # 把从EurekaServer上发现的服务名称，转换成全小写
      routes:
        - id: r1
          uri: lb://student-service
          predicates:
            - Path=/student/**
          filters:
            - StripPrefix=1

        - id: r2
          uri: lb://course-service
          predicates:
            - Path=/course/**
          filters:
            - StripPrefix=1